[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = "<enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Documents"
desc = "Cd to ~/Documents"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on   = [ "g", "G" ]
run  = "cd ~/Documents/Git"
desc = "Cd to ~/Documents/Git"
